// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqN2GjJIjuJxi2HFMnrRLSrN8ZWCmQeVQ',
    appId: '1:1096950170961:web:47980d579fc87b0bbf7f70',
    messagingSenderId: '1096950170961',
    projectId: 'bloodchain-ace5f',
    authDomain: 'bloodchain-ace5f.firebaseapp.com',
    storageBucket: 'bloodchain-ace5f.appspot.com',
    measurementId: 'G-31S3SG0VLY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZYIRFXT5nKonnLwj2f8a1r9DSmzgp6IE',
    appId: '1:1096950170961:android:6bd56a1f6cb1e834bf7f70',
    messagingSenderId: '1096950170961',
    projectId: 'bloodchain-ace5f',
    storageBucket: 'bloodchain-ace5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF-udueOt_X_6Irc3bIkOsOWiLJubPspA',
    appId: '1:1096950170961:ios:12ff3f7ca1f12a77bf7f70',
    messagingSenderId: '1096950170961',
    projectId: 'bloodchain-ace5f',
    storageBucket: 'bloodchain-ace5f.appspot.com',
    iosBundleId: 'com.example.grad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAF-udueOt_X_6Irc3bIkOsOWiLJubPspA',
    appId: '1:1096950170961:ios:e86d8d1af306139abf7f70',
    messagingSenderId: '1096950170961',
    projectId: 'bloodchain-ace5f',
    storageBucket: 'bloodchain-ace5f.appspot.com',
    iosBundleId: 'com.example.grad.RunnerTests',
  );
}
